### ISSUE TITLE
I/O using multiple NICs

### ISSUE THREAD

**Issue by gkatsikas** [tbarbette/fastclick#10]
Hi,

I have two machines with 4x10 Gbps NICs each, connected to each other as follows:

                      NIC 0    ---------------------- NIC 0
                      NIC 1    ---------------------- NIC 1
                   Machine 01                      Machine 02
                      NIC 2    ---------------------- NIC 2
                      NIC 3    ---------------------- NIC 3

On machine 01 I use MoonGen to send/receive 64-byte packets to/from both NICs.
On machine 02, I use Fast-Click to forward the packets back:
FromDPDKDevice(0) -> ToDPDKDevice(1, IQUEUE 1024);
FromDPDKDevice(1) -> ToDPDKDevice(0, IQUEUE 1024);
FromDPDKDevice(2) -> ToDPDKDevice(3, IQUEUE 1024);
FromDPDKDevice(3) -> ToDPDKDevice(2, IQUEUE 1024);

All NICs belong to the same NUMA socket and can share 8 cores in this socket (Intel Xeon). 
I start Fast-Click as follows: path/click -c ffff -n 4 -v -- my_example.click

The problem I see is that the throughput is not line rate (31.5 out of 40Gbps) when I inject packets of 60 bytes each. This is exactly what Figure 2 in the Fast-Click paper depicts.

If I use only one NIC from machine 01 to send/receive traffic, then throughput is maximum (14.88Mpps).
If I replace Fast-Click with a MoonGen application throughput is also maximum (40Gbps).

Is there any particular reason behind this degradation? Why Click is so much slower compared to MoonGen? Is it because of the virtua; function calls used by From/ToDPDKDevice elements?

I tried to configure the 2 elements by using more queues to read packets from (RSS). If I specify more than 4 queues (using MINQUEUES argument), the process crashes. How can I use 8 queues and 8 cores to scale?

Best regards,
Georgios

**Comment by tbarbette** [comment]
Hi,
I'm not familiar with moongen, could you give me the configuration to simply send and receive packets using 2 ports? And the one to forward using 2 ports?

What I saw with my x540 dual ports NIC is that packets cannot be received at line rate, 31 out of 40 is more or less what I found out, yes. Both with Netmap and DPDK. TX at 40G is not a problem though. What you're saying is that MoonGen can forward packets at 40G, with one or two cores per NIC?

If you use only one port per dual-port, you can achieve line rate. So I guessed the problem is with the dual port NICs and therefore concluded that was the limitation of the NICs as any tools, including DPDK's and Netmap's one couldn't achive more than ~33G of forwarding.
So your results surprise me. In your FastClick configuration with batching, the virtual call should not be the problem. I'd guess there could be a difference of DPDK configuration : offloadings activated in the NIC, cache, packet pool size, ... I'll check that with your MoonGen configure files and compare. I may have miss to activate/deactivate some fancy feature of the NIC allowing to RX at that rate. I don't support GRO in FastClick, if the packets are aggregated at RX, it could explain the difference.

By default the FromDPDKDevice elements will share all available threads (so here, 4 per FromDPDKDevice for 2 elements) and they will use one queue per thread automatically. I guess it craches because you have more queue than core and I didn't protect something. I suggest letting FromDPDKDevice handle the good number of queue, and just change the amount of threads. In that configuration one core per NIC should be enough, 2 at max. Having more queue will just slow down things. The amount of core is not the problem here.

Tom

**Comment by gkatsikas** [comment]
Hi,

I do not forwards traffic with MoonGen. Machine 01 above has 4 NICs and I start one Tx and one Rx thread per NIC (in two different cores) so each NIC is sending packets to Click and getting packets back from Click.
All 4 NICs operate at the same time, on the same CPU socket and they can Tx/Rx at line rate.
In Click, when 2 NICs kick in at the same time, throughput decreases from 14.88 to 11.7 Mpps.

I can send you my MoonGen script offline :)

Georgios

**Comment by tbarbette** [comment]
You achieved 40G with some configuration or not? I'm not sure to understand.

**Comment by tbarbette** [comment]
Any news on this? Can I close?

**Comment by gkatsikas** [comment]
You can close it for now. It has been quite some time since I did these experiments so I need to repeat them in order to confirm. My findings when using FastClick from my experiments match completely with the reported throughput in your paper though.
