### ISSUE TITLE
Example Configuration file Click-Netmap

### ISSUE THREAD

**Issue by hsrinireddy** [tbarbette/fastclick#16]
Hi Guys,

Thanks for the software, i found very interesting to use this software for my project.

I want to integrate click in user space on netmap, we were successfull on compiling the Click for netmap. But we are not sure on how to generate the click configuration file to perform some basic level testing.

As in the README.md document its specified only in single line
**An example configuration is : FromNetmapDevice(netmap:eth0) -> CheckIPHeader() -> ToNetmapDevice(netmap:eth1)** 
but when we open other Click configuration file in conf folder there were multiple lines.

Please help me on creating/procedure for generating Click configuration file for Netmap support.
Please share if any example configuration exists

Waiting for your prompt feedback

Regards,
Srinivas

**Comment by tbarbette** [comment]
Hi,

You'll have all the needed documentation here : http://www.read.cs.ucla.edu/click/docs/language

However the better way to do is probably to look at existing configurations, and steal som parts of them.

Just that to use Fastclick's Netmap you have to use FromNetmapDevice like you just said instead of a normal FromDevice.

Other example idem to the configuration you cite : 
`FromNetmapDevice(netmap:eth0) -> 
CheckIPHeader() -> 
ToNetmapDevice(netmap:eth1)  `

`fd :: FromNetmapDevice(netmap:eth0)
c:: CheckIPHeader()
td :: ToNetmapDevice(netmap:eth1)

fd-> c-> td`

**Comment by tbarbette** [comment]
How is it going from here?
