### ISSUE TITLE
Improved netmap version

### ISSUE THREAD

**Issue by collin-lekio** [tbarbette/fastclick#17]
Hi,

In the paper, ["Fast Userspace Packet Processing"](https://orbi.ulg.ac.be/bitstream/2268/181954/1/userspaceio.pdf) - you mention improvements done to netmap:

> We realized that our NICs have a feature whereby the
> status of a transmit packet ring can be mirrored in memory
> at very low performance cost. We modified Netmap to exploit
> this feature and also limited the release rate of packets
> consumed by the NIC to only recover buffer for sent packets
> once every interrupt, which released the PCIe bus of useless
> informations and brought Netmap performances above
> DPDK as we can see in figure 1

Where can this improved netmap code be found?

**Comment by tbarbette** [comment]
Hi,

You can find the TDWB change here : https://github.com/tbarbette/netmap, that is the part where instead of poking the device registers for the current tail pointer of the ring, we use the TD writeback feature, where the tail is written in any memory location you choose. The specific patch is this one : https://github.com/tbarbette/netmap/commit/c14ff0f93432c6326b45e7c31829dce035b1dda9

However after some rebase I lost the second part (I mostly moved to DPDK for my tests now) , but it is not complex, the fastclick code hasn't changed though, we can see here : 
https://github.com/tbarbette/fastclick/blob/master/elements/userlevel/tonetmapdevice.cc#L160
that I pass 1 instead of 0. I modified Netmap to only call the "reclaim" part if an interrupt has happened.

The two most important things in that Netmap version are the TDWB and the support for dynamic buffer allocation (IOCTLs NIOCALLOCBUFF and NIOCFREEBUF) which allows to dynamically release and allocate buffers.

I can try to dig into backups for the reclaim part, but it is not a big deal anymore as the TDWB make it much lighter anyway.

Note that those changes are IXGBE-specific, so it concerns all 82599-based nics. i40e use TDWB by default, including in the Netmap drivers. I guess that's why Luigi never merged the patch probably just moved on... He showed interest at that time though... Probably have too much to do.

**Comment by tbarbette** [comment]
Can I close this?
