### ISSUE TITLE
click utilizing 100% CPU regardless of traffic

### ISSUE THREAD

**Issue by maulikpatel1990** [tbarbette/fastclick#187]
I am trying to run below configuration and to me it seems like when there are no packets at any of the Unqueue element(upstream) it is continuously trying to pull the packets from upstream and because of that my CPU utilization reaches to almost 100%. Can anyone provide me any idea how can we aviod this 100% utilization?

FastUDPFlows -> Unqueue -> ARPQuerier -> Queue -> MultiReplayUnqueue -> ToDPDKDevice.

Thanks in advance.

**Comment by tbarbette** [comment]
Hi,

MultiReplayUnqueue is targeted to generate up to 100Gbps of traffic on a dedicated machine, hence it's just looping to send as much traffic as possible. We made it without any care for CPU consumption, only PPS.

What are you trying to do ?

**Comment by maulikpatel1990** [comment]
Hi Tom,

My use case is also similar. I want to generate traffic on a dedicated machine. But I want that in controlled manner, I mean I should be able to generate it with rate I provide. For that I have done some modification on MultiReplayUnqueue and as of now I am able to run it, but regardless of data rate I mean if I generate 100 packets per second(60 byte each resulting to around 48Kbps I think) then also I am getting 100% cpuusage.

Can you give me a reference/pointer to any other element in which I can look into for the same, I mean which does the same thing but also consider cpu usage in account?

Regards,
Maulik

**Comment by tbarbette** [comment]
If the rate you need is not super high, then RatedUnqueue or BandwidthRatedUnqueue should be fine. 
`FastUDPFlows -> BandwidthRatedUnqueue -> ARPQuerier -> ToDPDKDevice.`

Or even FastUDPFlows's RATE argument.
`FastUDPFlows(RATE X) -> Unqueue -> ToDPDKDevice.`

If you want to continue your way, can you give me the result of "sudo perf top -a -g" ? So I'll check which element is spinlooping. It may be also due to how you implemented your rate mechanism. How do you "wait" for tokens/allow to send more data? The way to go would be to unschedule MultiReplayUnqueue's task, and schedule a Timer.

**Comment by maulikpatel1990** [comment]
Hi Tom,

Again thanks for a quick response and sorry for coming back somewhat late on this.

Currently I am not running at too high rate but in my end application I may need to run at higher rate so I would like to stick with MultiReplayUnqueue element if possible.

Regarding my implementation of MultiReplayUnqueue, I am implementing TokenBucket to limit the Tx rate. And I am using "_timer.schedule_after(Timestamp::make_jiffies(_tb.time_until_contains(1)));" function re schedule a next callback if there is no token available.

I have taken a snapshot of perf command as you mentioned. Looking at that to me it seems like "FromDPDKDevice" is consuming more power.
![perf_output](https://user-images.githubusercontent.com/4986817/62558685-1a295680-b897-11e9-914e-b10ba3b12b6b.png)

Regards,
Maulik Patel

**Comment by maulikpatel1990** [comment]
Just to give you some overview of my system:

I am running fastclick(with userlevel DPDK) in CentOS 7 virtual machine created under Ubuntu 16.04. I am creating a virtual bridge interface in CentOS 7 and registering that bridge interface as DPDK.

Let me know if you have any confusion related to my setup. And is it possible that because of my setup I am getting 100% cpuusage?

**Comment by tbarbette** [comment]
So when you have a FromDPDKDevice element, and more generally when using DPDK, you always have a 100% usage because it's using polling, not interruption. In your configuration, it seems to be what happens and this is normal. When there will be real work to do, DPDK will not lose CPU time there. If you want to be able to revert to interruptions, then Netmap is a better idea.
