### ISSUE TITLE
What is the function of the fastclick metron branch?

### ISSUE THREAD

**Issue by ligang626** [tbarbette/fastclick#193]
What I am doing now is to display the fastclick port 80 as a rest device in onos.
And the device can see a network card

and then? What else can I do? What are the functions?

**Comment by gkatsikas** [comment]
Alright, with this step you have properly established Metron's data plane.
The ONOS UI is extended with 3 tabs (implemented by the server device driver), which you can access from the menu on the left. These tabs display latency, throughput, and CPU utilization per core. Can you see these tabs?

Now you need some control plane logic to pass network functions (or chains of network functions) to your data plane agent. To do so, you need the Metron controller module, which we implemented as an ONOS application that interacts with the server device driver.
We are planning to release the Metron controller with instructions on how to use it. Please hold tight and we will be back with some guidelines :)

**Comment by tbarbette** [comment]
We'll do that by the end of the week, so not in a very long time ;)

Once done, you give one or more NFV service chains to the controller that will synthesize them into (1) a set of classification rules for the traffic class, and (2) leftover operations, mainly stateful things such as a NAT, load balancer, and monitor CPU usage, basically a graph of FastClick elements.

The classification (1) will be installed to a switch before the server, or in the NIC if it is capable of flow classification. The controller then pushes message to the agent (that is the purpose of this branch) to execute the non-classification elements of the service chain (2), basically spawning FastClick sub-processes. According to the CPU load, the controller instructs the NIC to send some traffic classes to different CPUs, using parallel processing.

This scheme allows to offload all static classification to hardware, and avoid any software dispatching so packets do not jump between cores to be serviced here and there, reducing latency. That is basically a short summary of the Metron paper ;)

Technically, you could already send messages using the REST API to instruct the agent to start a chain : 
`curl http://SERVER/metron/chains -d '{"servicechains":[{"id":"dc00bf72-d29e-4e5d-9ce8-375330497685","rxFilter":{"method":"flow"},"configType":"click","config":"input[0] -> MarkIPHeader(OFFSET 14) -> filter1 :: IPFilter(allow any, deny all); lb :: RoundRobinIPMapper(- - 8.4.5.4 - 0 0, - - 8.4.5.5 - 0 0, - - 8.4.5.6 - 0 0, - - 8.4.5.2 - 0 0, - - 8.4.5.3 - 0 0); filter1[0] -> IPRewriter(lb, SET_AGGREGATE true) -> EtherRewrite(SRC 24:8A:07:58:C4:44, DST 24:8A:07:55:46:B1) -> [0]output; filter1[1] -> Discard;\n","cpus":"3","maxCpus":"5","autoScale":false,"nics":["fd0"]}]}'`
This will make the agent spawn a process to run a load balancer (on a single NIC, not very useful but it shows the idea^^) using 3 cores. Then you can push some rules to say which traffic should go to which cores, and send messages to use more or less cores, etc... Of course using the controller is a much better idea.

**Comment by gkatsikas** [comment]
The Metron controller is made public on my [github](https://github.com/gkatsikas/onos) as an ONOS app in the apps/metron folder of the ONOS tree.

We suggest that you use [metron-ctrl-1.15.0](https://github.com/gkatsikas/onos/tree/metron-ctrl-1.15.0) or [metron-ctrl-1.14.0](https://github.com/gkatsikas/onos/tree/metron-ctrl-1.14.0) branches. In the former branch, Metron is developed on top of ONOS 1.15.0, while in the latter branch Metron is based upon ONOS 1.14.0.
The code is the same, however, the way to build ONOS with Metron is slightly different.
ONOS 1.14.0 uses both BUCK and Bazel build tools, while ONOS 1.15.0 uses only Bazel (BUCK becomes deprecated).

You may consult the Metron controller [1.14.0](https://github.com/gkatsikas/onos/tree/metron-ctrl-1.14.0/apps/metron) or [1.15.0](https://github.com/gkatsikas/onos/tree/metron-ctrl-1.15.0/apps/metron) README files.

There is also a [metron-ctrl](https://github.com/gkatsikas/onos/tree/metron-ctrl/apps/metron) branch that ports Metron on top of the latest ONOS developments (i.e., master), but since ONOS faces transitions to a different subsystem, I suggest to avoid this brach for now.

**Comment by gkatsikas** [comment]
Any news on this topic?
Did you manage to run the metron controller along with the Metron FastClick agent?
