### ISSUE TITLE
Are there documentations for fastclick exclusive elements such as AggregateCounterVector?

### ISSUE THREAD

**Issue by strNewBee** [tbarbette/fastclick#327]
Can I find some documentations or example to understand this elements better?

**Comment by tbarbette** [comment]
In general the .hh fiels contains documentation (eg https://github.com/tbarbette/fastclick/blob/master/elements/analysis/aggcountervector.hh) which is exported to the wiki in  the elements page from time to time (https://github.com/tbarbette/fastclick/wiki/Elements), I did not do it since a few months.
Unfortunately that elements has not much documentation... I just updated it now
