### ISSUE TITLE
How to enable scattered mode in fastclick?

### ISSUE THREAD

**Issue by cxxuser** [tbarbette/fastclick#361]
I use fastclick to receive packets. I set the dataroom of the mbuf from 2048 to 64B. To receive large packets（>64B） with a 64B size dataroom mbuf, it reminds me that I need to enable scattered mode. So how can I enable scattered mode in fastclick?
![image](https://user-images.githubusercontent.com/40905208/171573960-6199787a-607b-4089-8f0f-2529517111ac.png)

**Comment by tbarbette** [comment]
It's currently not supported. It would be easy to enable, but then:
- either scattered buffers would end up in a different Packet objects (one per buffer). The second packet and subsequent would therefore look like garbage. Unless your pipeline is very simple it's not viable.
- we skip all "subsequent buffers" and only integrate the first buffer with the header as a Packet object. Internally, the subsequent buffers will be linked by DPDK but that will not be exposed to FastClick elements that will see a 64B packet. Therefore elements cannot access the payload of the "silently linked lists" buffers but it will be transmitted as one if forwarded to a DPDK Device.

Even if we imagine providing real support, it would lead to a general performance drop. We'll have to handle batches of linked lists of packets instead of batches of packets *everywhere*. Many "unlikely" conditions everywhere just for the scattered case...

A simple handling would be to copy scattered packets to a unique buffer, but that's sad.

The best course of action would be for Mellanox to send packets to different queues according to their size (like the Tilera they acquired), so we could have queues with different buffer size.

What's the use case?

**Comment by cxxuser** [comment]
I was inspired by the eurosys19 paper（make the most use of the last level cache）. And I try to send the packets larger than 64B all to one slice.

**Comment by cxxuser** [comment]
Thanks a lot for your suggestion, so all I wanted to do was test how much performance overhead it would be.

**Comment by cxxuser** [comment]
I also think your method is the most reasonable one at the moment for the use of NUCA properties. However, I also want to measure how much performance loss other methods have, so I want to turn on the scattered mode in fastclick.

**Comment by tbarbette** [comment]
I'll close the issue because right now it's not supported.

We can discuss ways to implement something though. Maybe we can discuss this offline? tom.barbette@uclouvain.be

**Comment by cxxuser** [comment]
Okey
